name: build-artifact

permissions:
  contents: write

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Run
        run: |
          npm i pnpm -g

          pnpm install

          pnpm run package

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: jump-easy
          path: "*.vsix"

      - uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: "*.vsix"
